### PR TITLE
Upon request, I shortened the words.

### PR DESCRIPTION
**Pull request by C0la149**

### CODE REVIEW

**Comment by jb-alvarado** [comment]
I think something went wrong here, because there is a conflict and it looks like some things of this commit exists already. Every time the original repo has changed, you should sync to fork:
Bildschirmfoto vom 2024-05-13 07-25-38

**Comment by C0la149** [comment]
How can I synchronize? I just don't know much about Github.

**Comment by C0la149** [comment]
How can I synchronize? I just don't know much about Github.

**Comment by jb-alvarado** [comment]
You see it on the screenshot I posted. You need to click on sync and then **update branch**. When there is a conflict, you could copy your last changes, reset your fork and apply the changes again.

**Review by C0la149 — COMMENTED** [review]
.

**Pull request closed without merging**
